# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/zboard/zboard.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zboard || ORIG_REF_NAME==zboard}]

# IP: bd/zboard/ip/zboard_processing_system7_0_1/zboard_processing_system7_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zboard_processing_system7_0_1 || ORIG_REF_NAME==zboard_processing_system7_0_1}]

# IP: bd/zboard/ip/zboard_axi_slave_0_1/zboard_axi_slave_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zboard_axi_slave_0_1 || ORIG_REF_NAME==zboard_axi_slave_0_1}]

# IP: bd/zboard/ip/zboard_processing_system7_0_axi_periph_1/zboard_processing_system7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zboard_processing_system7_0_axi_periph_1 || ORIG_REF_NAME==zboard_processing_system7_0_axi_periph_1}]

# IP: bd/zboard/ip/zboard_rst_processing_system7_0_100M_1/zboard_rst_processing_system7_0_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zboard_rst_processing_system7_0_100M_1 || ORIG_REF_NAME==zboard_rst_processing_system7_0_100M_1}]

# IP: bd/zboard/ip/zboard_auto_pc_1/zboard_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zboard_auto_pc_1 || ORIG_REF_NAME==zboard_auto_pc_1}]

# IP: bd/zboard/ip/zboard_auto_us_1/zboard_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zboard_auto_us_1 || ORIG_REF_NAME==zboard_auto_us_1}]

# XDC: bd/zboard/ip/zboard_processing_system7_0_1/zboard_processing_system7_0_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zboard_processing_system7_0_1 || ORIG_REF_NAME==zboard_processing_system7_0_1}] {/inst }]/inst ]]

# XDC: bd/zboard/ip/zboard_rst_processing_system7_0_100M_1/zboard_rst_processing_system7_0_100M_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zboard_rst_processing_system7_0_100M_1 || ORIG_REF_NAME==zboard_rst_processing_system7_0_100M_1}] {/U0 }]/U0 ]]

# XDC: bd/zboard/ip/zboard_rst_processing_system7_0_100M_1/zboard_rst_processing_system7_0_100M_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zboard_rst_processing_system7_0_100M_1 || ORIG_REF_NAME==zboard_rst_processing_system7_0_100M_1}] {/U0 }]/U0 ]]

# XDC: bd/zboard/ip/zboard_rst_processing_system7_0_100M_1/zboard_rst_processing_system7_0_100M_1_ooc.xdc

# XDC: bd/zboard/ip/zboard_auto_pc_1/zboard_auto_pc_1_ooc.xdc

# XDC: bd/zboard/ip/zboard_auto_us_1/zboard_auto_us_1_ooc.xdc

# XDC: bd/zboard/ip/zboard_auto_us_1/zboard_auto_us_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zboard_auto_us_1 || ORIG_REF_NAME==zboard_auto_us_1}] {/inst }]/inst ]]

# XDC: bd/zboard/zboard_ooc.xdc
